#!/usr/bin/env bash
set -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

# Get current username
USERNAME=$(whoami)
FLAKE_SYSTEM="darwinConfigurations.${USERNAME}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo -e "${YELLOW}Building configuration for user: ${USERNAME}${NC}"
echo -e "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@

echo -e "${YELLOW}Switching to new generation...${NC}"
if [ "$(id -u)" -ne 0 ]; then
  sudo ./result/sw/bin/darwin-rebuild switch --flake .#${USERNAME} $@
else
  ./result/sw/bin/darwin-rebuild switch --flake .#${USERNAME} $@
fi

echo -e "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo -e "${GREEN}Switch to new generation complete!${NC}"
