#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

# Get current username
USERNAME=$(whoami)

export NIXPKGS_ALLOW_UNFREE=1

echo -e "${YELLOW}Building home-manager configuration for user: ${USERNAME}${NC}"
echo -e "${YELLOW}Starting build...${NC}"

# Build and activate home-manager configuration
nix --extra-experimental-features 'nix-command flakes' run .#homeConfigurations.${USERNAME}.activationPackage $@

echo -e "${GREEN}Home-manager switch complete!${NC}"