wireplumber.components = [
  {
    name = dji-hide-sink.lua, type = script/lua
    provides = custom.dji-hide-sink
  }
]

wireplumber.profiles = {
  main = {
    custom.dji-hide-sink = required
  }
}
